SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[FI_SP_IncBenef]
    @NOME          VARCHAR (50),
	@CPF           VARCHAR (11),
	@IDCLIENTE     BIGINT,
	@ID			   BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
	VALUES (@CPF, @NOME, @IDCLIENTE);

	SELECT SCOPE_IDENTITY();
END
GO
